export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST"
export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST"
export const FETCH_DELETE_POST_REQUEST = 'FETCH_DELETE_POST_REQUEST'
export const FETCH_ADD_POST_REQUEST = 'FETCH_ADD_POST_REQUEST'
export const FETCH_EDIT_POST_REQUEST = 'FETCH_EDIT_POST_REQUEST'

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_POST_COMMENTS_SUCCESS = "FETCH_POST_COMMENTS_SUCCESS"
export const FETCH_DELETE_POST_SUCCESS  = 'FETCH_DELETE_POST_SUCCESS'
export const FETCH_ADD_POST_SUCCESS  = 'FETCH_ADD_POST_SUCCESS'
export const FETCH_EDIT_POST_SUCCESS  = 'FETCH_EDIT_POST_SUCCESS'


export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE"
export const FETCH_DELETE_POST_ERROR = "FETCH_DELETE_POST_ERROR"
export const FETCH_EDIT_POST_ERROR = "FETCH_EDIT_POST_ERROR"
export const FETCH_ADD_POST_ERROR = 'FETCH_ADD_POST_ERROR'





